# Generated by Django 5.1.1 on 2024-10-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_promociones'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehículo',
            name='año',
            field=models.CharField(default=2024, max_length=4),
            preserve_default=False,
        ),
    ]
