# Generated by Django 5.1.1 on 2024-10-10 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_vehículo_año'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='enganche',
        ),
    ]
