# Generated by Django 5.1.1 on 2024-10-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_vehículo_enganche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehículo',
            name='enganche',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
