# Generated by Django 5.1.1 on 2024-10-10 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_alter_vehículo_enganche'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehículo',
            name='enganche',
        ),
    ]
