# Generated by Django 5.1.1 on 2024-10-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_remove_vehículo_enganche'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehículo',
            name='enganche',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
