# Generated by Django 5.1.3 on 2024-12-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_alter_plan_mensualidades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehículo',
            name='especificaciones',
        ),
        migrations.AddField(
            model_name='vehículo',
            name='transmision',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='vehículo',
            name='interesAnual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehículo',
            name='interesMensual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
