# Generated by Django 5.1.3 on 2024-12-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_remove_vehículo_especificaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehículo',
            name='transmision',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
