# Generated by Django 5.1.3 on 2024-12-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_alter_vehículo_transmision'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehículo',
            name='cilindros',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehículo',
            name='tipoCombustible',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='vehículo',
            name='traccion',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
