# Generated by Django 5.1.3 on 2024-12-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_vehículo_cilindros_vehículo_tipocombustible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehículo',
            name='transmision',
            field=models.CharField(blank=True, choices=[('a', 'Automático'), ('m', 'manual'), ('', '')], default='', max_length=1, null=True),
        ),
    ]
