# Generated by Django 5.1.3 on 2024-12-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0013_alter_vehículo_transmision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehículo',
            name='tipoCombustible',
        ),
        migrations.AddField(
            model_name='vehículo',
            name='combustible',
            field=models.CharField(blank=True, choices=[('gas', 'Gasolina'), ('diesel', 'Diesel'), ('electricity', 'Eléctrico'), ('', 'Sin definir')], default='', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='vehículo',
            name='traccion',
            field=models.CharField(blank=True, choices=[('fwd', 'Delantera'), ('rwd', 'Trasera'), ('4wd', '4x4'), ('', 'Sin definir')], default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='vehículo',
            name='transmision',
            field=models.CharField(blank=True, choices=[('a', 'Automático'), ('m', 'Manual'), ('', 'Sin definir')], default='', max_length=1, null=True),
        ),
    ]
